Added locators
Den2137/g2-cypress-sandbox pull request #1
Opened 2023-04-23 15:13 UTC by Den2137

Added locators to dropdown "Commands"  to index.html, cypress-api.html, todo.html, utilities.html

2023-04-24 21:13 UTC, SanitarskyiDmytro requested changes
Те що зроблено - правильно, але це не все.
Якщо, наприклад, перейдете на /commands/querying , то там атрибутів вже не буде, потрібно це доробити

2023-04-26 18:47 UTC, Den2137 commented
Добавил локаторы в команды.

2023-04-27 09:56 UTC, SanitarskyiDmytro approved these changes

2023-05-01 10:59 UTC, SanitarskyiDmytro approved these changes

2023-05-16 21:28 UTC, merged